apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-rolebinding
  namespace: jenkins-namespace
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-namespace
roleRef:
  kind: Role
  name: jenkins-secrets-reader
  apiGroup: rbac.authorization.k8s.io