apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-namespace
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv-data/mongodb"
