apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring-namespace
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      name: prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus.monitoring-namespace.svc:9090
      version: 1
