namespace: jenkins-namespace

jenkinsMaster:
  image: jenkins/jenkins:latest
  imagePullPolicy: IfNotPresent
  services:
      jenkinsmasternodeport:
        type: NodePort
        ports:
          port: 8080
          targetport: 8080
          nodePort: 31000  # NodePort for port 8080
      jenkinsmasterclusterip:
        type: ClusterIP
        ports:
          port: 50000   # New ClusterIP port for JNLP
          targetport: 50000
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"
  volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-pvc
  

controller:
  installPlugins:
    - kubernetes:1.30.7
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.10.0
    - configuration-as-code:1.55
    - token-macro:266.v44a80cf277fd
    - json-path-api:2.8.0-5.v07cb_a_1ca_738c
    # Add other plugins that were failing due to missing dependencies
    - favorite:2.3.3
    - github-branch-source:2.11.3
    - blueocean:1.24.7
    - blueocean-rest-impl:1.24.7
    - blueocean-pipeline-api-impl:1.24.7
    # Add any other plugins you need
    - github:1.39.0
    - github-branch-source:1789.v5b_0c0cea_18c3
    - blueocean-git-pipeline:1.27.12
    - blueocean-github-pipeline:1.27.12
    - blueocean-pipeline-editor:1.27.12
    - blueocean-bitbucket-pipeline:1.27.12
    - blueocean-rest-impl:1.27.12
    - blueocean-events:1.27.12

persistence:
  enabled: true
  storageClass: "standard"  # Adjust according to your storage class
  accessMode: ReadWriteOnce
  size: 10Gi

service:
  type: NodePort
  port: 8080
  nodePort: 31000

ingress:
  enabled: false

serviceAccount:
  create: true
  name: jenkins-sa
  annotations:
    key1: value1
    key2: value2
  automount: true
