# templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-pod-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-namespace
roleRef:
  kind: Role
  name: jenkins-pod-creator
  apiGroup: rbac.authorization.k8s.io
